# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb6f93cce149e4dc41fc95ccf6a99d1958f10df43bae768dcc18b49ad4638ef965968b98b834355759ff487fbd3c0f93d9ba7b42d2ef2b8c368ed89cb1a964a6

test:
  secret_key_base: b911ef64c061bba8cdd1f2437b4c7e5d666be4c2aad29e3ea3461deae4963474ba4321c14433c276f7a2259af68d2560a17dacd640907c7a5b4885b5e6f85f8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
